routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomePageController@index');
Route::get('our-room/{slug}', 'HomePageController@room')->name('our-room');
Route::get('/book-room', 'HomePageController@bookRoom')->name('book-room');

Route::get('/testimonies', 'TestimonyController@index');
Route::post('/testimonies', 'TestimonyController@store');
Route::get('/testimonies/new', function () {
	return view('testing.testimony.form');
});
Route::get('/testimonies/{testimonyId}/edit', 'TestimonyController@edit');
Route::post('/testimonies/{testimonyId}/edit', 'TestimonyController@update');
Route::post('/testimonies/{testimonyId}/delete', 'TestimonyController@delete');

Route::get('/facilities', 'FacilityController@index');
Route::post('/facilities', 'FacilityController@store');
Route::get('/facilities/new', function () {
	return view('testing.facility.form');
});
Route::get('/facilities/{facilityId}/edit', 'FacilityController@edit');
Route::post('/facilities/{facilityId}/edit', 'FacilityController@update');
Route::post('/facilities/{facilityId}/delete', 'FacilityController@delete');

Route::get('/config/header', 'ConfigurationController@editHeaderSection');
Route::put('/config/header', 'ConfigurationController@updateHeaderSection');

Route::get('/config/service', 'ConfigurationController@editServiceSection');
Route::put('/config/service', 'ConfigurationController@updateServiceSection');

Route::get('/config/room', 'ConfigurationController@editRoomSection');
Route::put('/config/room', 'ConfigurationController@updateRoomSection');

Route::get('/config/general', 'ConfigurationController@editGeneralSection');
Route::put('/config/general', 'ConfigurationController@updateGeneralSection');

Route::get('/config/about', 'ConfigurationController@editAboutSection');
Route::put('/config/about', 'ConfigurationController@updateAboutSection');

Route::post('/media', 'ConfigurationController@addMedia');
Route::delete('/media/{mediaId}', 'ConfigurationController@destroyMedia');

// room route
Route::resource('/rooms','RoomController');
Route::get('rooms/room-images/{id}', 'RoomController@formRemoveImage');

Route::delete('/rooms/room-images/{$id}', 'RoomController@removeImage');
Route::resource('room-facility', 'RoomFacilityController', ['except' => 'show']);


Route::get('/home', 'HomeController@index')->name('home');

Route::group([
	'namespace' => 'Auth'
],
	function () {

		// Authentication Routes...
		$this->get('login', 'LoginController@showLoginForm')->name('login');
		$this->post('login', 'LoginController@login');
		$this->post('logout', 'LoginController@logout')->name('logout');

	});

app/Models/Room.php
<?php

namespace App\Models;

use App\Exceptions\RoomInvalidArgumentException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Storage;
use Ramsey\Uuid\Uuid;
use Illuminate\Support\Str;
use Parsedown;

class Room extends Model
{
    /**
     * @var string
     */
    protected $table='rooms';

    /**
     * @var array
     */
    protected $fillable=[
    	'name',
        'price',
        'detail'
    ];

    /**
     * set title attribute and automatically slug
     *
     * @param string $value
     *
     * */

        public function setNameAttribute($value)
        {
            $this->attributes['name'] = $value;
            if (! $this->exists){
                $this->setUniqueSlug($value, '');
            }
        }
    /**
     * recursive routine to set unique slug automatically
     *
     * @param string $title
     * @param mixed $extra
     *
     * */

    protected function setUniqueSlug($title, $extra)
    {
        $uuid = Uuid::uuid1();
        $slug = Str::slug($title.'-'.$extra);
        if (static::whereSlug($slug)->exists()){
            // upgrade php 7.1 can't use number
            $this->setUniqueSlug($title,$extra .$uuid->toString());
            return;
        }
        $this->attributes['slug'] = $slug;

    }

    /**
     * get excerpt of detail room
     *
     * @return String
     */
    public function getExcerptAttribute(): String
    {
        $markdown = new Parsedown();

        $content =  Str::limit($this->detail);
        return $markdown->text($content);
    }

    /**
     * get price room
     *
     * @return string
     */
    public function getHargaAttribute(){
        return "Rp " . number_format($this->price,2,',','.');
    }

    /**
     * get image url attribute mutator
     *
     * @param $value
     * @return mixed
     */
    public function getImageAttribute($value)
    {
        return Storage::url("rooms/{$value}");
    }

    /**
     * @return mixed
     */
    public function getCoverAttribute(){
        return Storage::url("{$this->images()->first()->src}");
    }

    /**
     * relationship between room and room facility many to many
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function room_facilities(){
        return $this->belongsToMany(RoomFacility::class, 'room_facility_pivot');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images(){
    	return $this->hasMany(RoomImage::class, 'room_id');
    }

//    protected static function boot() {
//        parent::boot();
//
//        static::deleting(function($room) { // before delete() method call this
//            $room->images()->delete();
//            // do the rest of the cleanup...
//        });
//    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/homepage.blade.php
@extends('layouts.app', [
'title' => 'Sunset Point Hotel'])

@section('content')

@include('home.header')
@include('home.facility')
@include('home.room')
@include('home.testimoni')
@include('home.about')
@endsection

resources/views/room_book.blade.php
@extends('layouts.app')

@section('content')
<section id="room-content">
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-6">
            <form action="">
                <div class="form-group">
                    <label for="exampleInputEmail1">Contact Name</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="contact name">
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Phone</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="phone">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="email">
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Guest Name</label>
                    <input type="email" class="form-control col-md-6" id="exampleInputEmail1" placeholder="Guest Name">
                </div>
            </form>
        </div>
        <div class="col-md-6 col-lg-6">
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Additional Request</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>

            <div class="row custom-row-book-room">
                <p>$ 100.00;</p>
                <a href={{ url("/")}} class="btn btn-orange">Book Now ! <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>
</div>
<br><br><br>
</section>
@endsection 

resources/views/roompage.blade.php
@extends('layouts.app', [
  'title' => 'Sunset Point Hotel'])

@section('content')

    <section id="room-content">
        <div class="container">
            <div class="row">
                <div class="col-md-8 wow fadeInLeft animation-delay-3">
                    <div class="slide">
                        <ul id="lightSlider">
                            @foreach($room->images as $media)
                                <li data-thumb="{{ asset($media->thumbs) }}">
                                    <img src="{{ asset($media->url) }}" />
                                </li>
                            @endforeach
                        </ul>
                    </div>

                    <div class="content">

                        <div class="name-price d-flex align-items-center" style="margin-bottom: 8px;">
                            <h1 class="title">{{ $room->name }}</h1>
                            <div class="price">
                                <p>Start from <span>{{ $room->harga }}</span> / night</p>
                            </div>
                        </div>
                        <hr>

                        <div class="room-facility">
                            <ul class="list-inline">
                                @foreach($room->room_facilities as $index => $facility)
                                    <li class="list-inline-item wow fadeInDown animation-delay-{{ $index+1 }}">
                                        <img src="{{ asset($facility->image) }}" alt="{{ $facility->name }}" />{{ $facility->name }}
                                    </li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="room-details wow fadeInUp animation-delay-5">
                            <h2 class="details">Rooms Details </h2>
                            {!! $room->detail !!}
                        </div>

                    </div>
                </div>
                <div class="sidebar col-md-4 wow fadeInRight">
                    <div class="card-header title ">More Our Room</div>
                    <ul class="card list-unstyled">
                        @foreach($latests as $index => $latest)
                            <li class="card-body media wow fadeInDown animation-delay-{{ $index+1 }}">
                                @if(count($latest->images))
                                <a href="{{ route('our-room', $latest->slug) }}">
                                    <img height="40px" class="mr-3" src="{{ app('url')->asset($latest->images->first()->thumbs) }}" alt="{{ $latest->name }}">
                                </a>
                                @endif

                                <div class="media-body">
                                    <a href="{{ route('our-room', $latest->slug) }}">
                                        <h5 class="text-dark font-weight-bold mt-0 mb-1">{{ $latest->name }}</h5>
                                        <p class="text-muted">Start from {{ $latest->harga }} / night</p>
                                    </a>
                                    <hr>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                    <div>
                        <a href={{route('book-room')}} class="btn btn-block btn-custom" >Review</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection