routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomePageController@index');
Route::get('our-room/{slug}', 'HomePageController@room')->name('our-room');
Route::get('/book-room', 'HomePageController@bookRoom')->name('book-room');

Route::get('/testimonies', 'TestimonyController@index');
Route::post('/testimonies', 'TestimonyController@store');
Route::get('/testimonies/new', function () {
	return view('testing.testimony.form');
});
Route::get('/testimonies/{testimonyId}/edit', 'TestimonyController@edit');
Route::post('/testimonies/{testimonyId}/edit', 'TestimonyController@update');
Route::post('/testimonies/{testimonyId}/delete', 'TestimonyController@delete');

Route::get('/facilities', 'FacilityController@index');
Route::post('/facilities', 'FacilityController@store');
Route::get('/facilities/new', function () {
	return view('testing.facility.form');
});
Route::get('/facilities/{facilityId}/edit', 'FacilityController@edit');
Route::post('/facilities/{facilityId}/edit', 'FacilityController@update');
Route::post('/facilities/{facilityId}/delete', 'FacilityController@delete');

Route::get('/config/header', 'ConfigurationController@editHeaderSection');
Route::put('/config/header', 'ConfigurationController@updateHeaderSection');

Route::get('/config/service', 'ConfigurationController@editServiceSection');
Route::put('/config/service', 'ConfigurationController@updateServiceSection');

Route::get('/config/room', 'ConfigurationController@editRoomSection');
Route::put('/config/room', 'ConfigurationController@updateRoomSection');

Route::get('/config/general', 'ConfigurationController@editGeneralSection');
Route::put('/config/general', 'ConfigurationController@updateGeneralSection');

Route::get('/config/about', 'ConfigurationController@editAboutSection');
Route::put('/config/about', 'ConfigurationController@updateAboutSection');

Route::post('/media', 'ConfigurationController@addMedia');
Route::delete('/media/{mediaId}', 'ConfigurationController@destroyMedia');

// room route
Route::resource('/rooms','RoomController');
Route::get('rooms/room-images/{id}', 'RoomController@formRemoveImage');

Route::delete('/rooms/room-images/{$id}', 'RoomController@removeImage');
Route::resource('room-facility', 'RoomFacilityController', ['except' => 'show']);


Route::get('/home', 'HomeController@index')->name('home');

Route::group([
	'namespace' => 'Auth'
],
	function () {

		// Authentication Routes...
		$this->get('login', 'LoginController@showLoginForm')->name('login');
		$this->post('login', 'LoginController@login');
		$this->post('logout', 'LoginController@logout')->name('logout');

	});

app/Models/Room.php
<?php

namespace App\Models;

use App\Exceptions\RoomInvalidArgumentException;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Storage;
use Ramsey\Uuid\Uuid;
use Illuminate\Support\Str;
use Parsedown;

class Room extends Model
{
    /**
     * @var string
     */
    protected $table='rooms';

    /**
     * @var array
     */
    protected $fillable=[
    	'name',
        'price',
        'detail'
    ];

    /**
     * set title attribute and automatically slug
     *
     * @param string $value
     *
     * */

        public function setNameAttribute($value)
        {
            $this->attributes['name'] = $value;
            if (! $this->exists){
                $this->setUniqueSlug($value, '');
            }
        }
    /**
     * recursive routine to set unique slug automatically
     *
     * @param string $title
     * @param mixed $extra
     *
     * */

    protected function setUniqueSlug($title, $extra)
    {
        $uuid = Uuid::uuid1();
        $slug = Str::slug($title.'-'.$extra);
        if (static::whereSlug($slug)->exists()){
            // upgrade php 7.1 can't use number
            $this->setUniqueSlug($title,$extra .$uuid->toString());
            return;
        }
        $this->attributes['slug'] = $slug;

    }

    /**
     * get excerpt of detail room
     *
     * @return String
     */
    public function getExcerptAttribute(): String
    {
        $markdown = new Parsedown();

        $content =  Str::limit($this->detail);
        return $markdown->text($content);
    }

    /**
     * get price room
     *
     * @return string
     */
    public function getHargaAttribute(){
        return "Rp " . number_format($this->price,2,',','.');
    }

    /**
     * get image url attribute mutator
     *
     * @param $value
     * @return mixed
     */
    public function getImageAttribute($value)
    {
        return Storage::url("rooms/{$value}");
    }

    /**
     * @return mixed
     */
    public function getCoverAttribute(){
        return Storage::url("{$this->images()->first()->src}");
    }

    /**
     * relationship between room and room facility many to many
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function room_facilities(){
        return $this->belongsToMany(RoomFacility::class, 'room_facility_pivot');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images(){
    	return $this->hasMany(RoomImage::class, 'room_id');
    }

//    protected static function boot() {
//        parent::boot();
//
//        static::deleting(function($room) { // before delete() method call this
//            $room->images()->delete();
//            // do the rest of the cleanup...
//        });
//    }

}

resources/views/testing/config/general.blade.php
@extends('layouts.admin', [
'title' => 'General Setting'
])

@section('content')
    <div class="card-body">
        <form method="POST" action="{{ url('/config/general') }}" enctype="multipart/form-data">
            <input type="hidden" name="_method" value="PUT">
            {{ csrf_field() }}

            <h3 class="mb-2">Logo</h3>

            @if(!empty($general->logo))
                <img src="{{ url($general->logo) }}" class="img-fluid mx-auto mb-2">
            @endif

            <div class="form-group">
                <label class="" for="logo">Logo</label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="logo" name="logo" accept="image/*">
                    <label class="custom-file-label" id="logoLabel" for="logo" data-placeholder="Choose logo...">
                        Choose logo...
                    </label>
                </div>
            </div>

            <h3>Contact</h3>
            <div class="form-group">
                <label for="phone" class="col-form-label">Phone</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text fa fa-phone" id="phone"></span>
                    </div>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ $general->phone }}" placeholder="Input phone...">
                    <div class="invalid-feedback">
                        Please input phone.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-form-label">Email</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text fa fa-envelope" id="email"></span>
                    </div>
                    <input type="text" class="form-control" id="email" name="email"  placeholder="Input email..."  value="{{ $general->email }}">
                    <div class="invalid-feedback">
                        Please input email.
                    </div>
                </div>
            </div>

            <h3 class="mb-2">Location</h3>
            <div class="form-group">
                <textarea name="location" id="subtitle" class="form-control" placeholder="Please enter location..." required>
                    {{ $general->location }}
                </textarea>

                <div class="invalid-feedback">
                    Please input location.
                </div>
            </div>

            <h3 class="mb-2">Social media</h3>
            <div class="form-group">
                <label for="facebook" class="sr-only">Facebook</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="facebook">https://facebook.com/</span>
                    </div>
                    <input type="text" class="form-control" id="facebook" name="facebook_user" value="{{ $general->facebook_user }}" placeholder="Username">
                    <div class="invalid-feedback">
                        Please input facebook username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="facebook" class="sr-only">Twitter</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="twitter">https://twitter.com/</span>
                    </div>
                    <input type="text" class="form-control" id="twitter" name="twitter_user"  value="{{ $general->twitter_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input twitter username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="youtube" class="sr-only">Youtube</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="youtube">https://www.youtube.com/</span>
                    </div>
                    <input type="text" class="form-control" id="youtube" name="youtube_user"  value="{{ $general->youtube_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input youtube username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="google-plus" class="sr-only">Google Plus</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="google-plus">https://plus.google.com/</span>
                    </div>
                    <input type="text" class="form-control" id="google-plus" name="google_plus_user"  value="{{ $general->google_plus_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input google plus username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="instagram" class="sr-only">Instagram</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="instagram">https://instagram.com/</span>
                    </div>
                    <input type="text" class="form-control" id="instagram" name="instagram_user"  value="{{ $general->instagram_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input Instagram username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="linkedin" class="sr-only">Linked In</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="linkedin">https://linkedin.com/</span>
                    </div>
                    <input type="text" class="form-control" id="linkedin" name="linkedin_user"  value="{{ $general->linkedin_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input Linkedin username.
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="pinterest" class="sr-only">Pinterest</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="pinterest">https://pinterest.com/</span>
                    </div>
                    <input type="text" class="form-control" id="pinterest" name="pinterest_user"  value="{{ $general->pinterest_user }}"  placeholder="Username">
                    <div class="invalid-feedback">
                        Please input Pinterest username.
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
@endsection

@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
    <script>
        $(document).ready(function () {
            $("#logo").on('change', function (event) {
                var placeholder = $("#logoLabel").data('placeholder')

                if (event.target.files.length) {
                    placeholder = '';

                    for (var index = 0; index < event.target.files.length; index++) {
                        if (index > 0) {
                            placeholder += ", ";
                        }

                        placeholder += event.target.files[index].name
                    }
                }

                $("#logoLabel").html(placeholder)
            })
        })
    </script>
@endpush

resources/views/testing/config/header.blade.php
@extends('layouts.admin', [
'title' => 'Header Setting'
])

@section('content')
    <div class="card-body">
        <form method="POST" action="{{ url('/config/header') }}"  enctype="multipart/form-data">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            <div class="d-flex align-items-center" style="margin-bottom: 8px;">
                <label class="control-label" style="margin: 0;">Titles</label>
                <div class="btn btn-danger btn-sm add-more-title ml-auto">
                    <i class="fa fa-plus"></i>
                    Add
                </div>
            </div>

            <div class="form-group title">
                @foreach($header->title as $title)
                    <div class="input-group copy" style="margin-bottom: 8px;">
                        <input type="text" class="form-control" id="title" name="title[]" placeholder="Please enter title..." value="{{ $title }}" required />
                        <div class="input-group-prepend">
                            <div type="button" class="btn btn-default remove-title-input"><i class="fa fa-minus"></i></div>
                        </div>
                    </div>
                @endforeach

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a title </div>
            </div>

            <div class="form-group">
                <label for="subtitle">Subtitle</label>
                <textarea name="subtitle" id="subtitle" class="form-control" placeholder="Please enter subtitle...">
                    {{ $header->subtitle }}
                </textarea>

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a subtitle </div>
            </div>

            <label class="control-label" style="margin: 0;">Cover</label>
            <br />

            @if(!empty($header->cover))
                <img src="{{ url($header->cover) }}" class="img-fluid mx-auto pb-2">
            @endif

            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="cover" name="cover" value="" accept="image/*">
                    <label class="custom-file-label" for="cover" id="coverLabel" data-placeholder="Choose header cover photo...">
                        Choose header cover photo...
                    </label>
                </div>
            </div>

            <div class="d-flex justify-content-center">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-save"></i>
                    Save</button>
            </div>
        </form>
    </div>
@endsection

@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
    <script>
        $(document).ready(function() {
            $("body").on("click", ".add-more-title", function () {
                $(".form-group.title").append(
                    `<div class="input-group copy" style="margin-bottom: 8px;">
                <input type="text" class="form-control" id="title" name="title[]" placeholder="Please enter title..." value="" required />
                <div class="input-group-prepend">
                    <div type="button" class="btn btn-default remove-title-input"><i class="fa fa-minus"></i></div>
                </div>
            </div>`
                )
            });

            $("body").on("click", ".remove-title-input", function () {
                $(this).closest('.input-group.copy').remove();
            })

            $("#cover").on('change', function (event) {
                var placeholder = $("#coverLabel").data('placeholder')

                if (event.target.files.length) {
                    placeholder = '';

                    for (var index = 0; index < event.target.files.length; index++) {
                        if (index > 0) {
                            placeholder += ", ";
                        }

                        placeholder += event.target.files[index].name
                    }
                }

                $("#coverLabel").html(placeholder)
            })
        });
    </script>
@endpush

resources/views/testing/config/room.blade.php
@extends('layouts.admin', [
'title' => 'Room Setting'
])

@section('content')
    <div class="card-body">
        <form method="POST" action="{{ url('/config/room') }}">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            <div class="form-group title">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ $room->title }}" placeholder="Please enter title..." required>

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a title </div>
            </div>

            <div class="form-group">
                <label for="subtitle">Subtitle</label>
                <textarea name="subtitle" id="content subtitle" class="form-control" placeholder="Please enter subtitle...">
                        {{ $room->subtitle }}
                    </textarea>

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a subtitle </div>
            </div>

            <div class="d-flex justify-content-center">
                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
            </div>
        </form>
    </div>
@endsection

@push('styles')
<link rel="stylesheet" type="text/css" href="{{ asset('css/editor.css') }}">
@endpush

@push('scripts')
<script src="{{ asset('js/editor.js') }}"></script>
@endpush

resources/views/testing/config/service.blade.php
@extends('layouts.admin', [
'title' => 'Service Setting'
])

@section('content')
    <div class="card-body">
        <form method="POST" action="{{ url('/config/service') }}"  enctype="multipart/form-data">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            <div class="form-group title">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="{{ $service->title }}" placeholder="Please enter title..." required>

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a title </div>
            </div>

            <div class="form-group">
                <label for="subtitle">Subtitle</label>
                <textarea name="subtitle" id="content" class="form-control" placeholder="Please enter subtitle...">
                    {!! $service->subtitle !!}
                </textarea>

                <div class="valid-feedback"> Looks good! </div>
                <div class="invalid-feedback"> Please input a subtitle </div>
            </div>

            <div class="d-flex justify-content-center">
                <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
            </div>
        </form>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $("#cover").on('change', function (event) {
                var placeholder = $("#coverLabel").data('placeholder')

                if (event.target.files.length) {
                    placeholder = '';

                    for (var index = 0; index < event.target.files.length; index++) {
                        if (index > 0) {
                            placeholder += ", ";
                        }

                        placeholder += event.target.files[index].name
                    }
                }

                $("#coverLabel").html(placeholder)
            })
        })
    </script>
@endpush