routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomePageController@index');
Route::get('our-room/{slug}', 'HomePageController@room')->name('our-room');
Route::get('/book-room', 'HomePageController@bookRoom')->name('book-room');

Route::get('/testimonies', 'TestimonyController@index');
Route::post('/testimonies', 'TestimonyController@store');
Route::get('/testimonies/new', function () {
	return view('testing.testimony.form');
});
Route::get('/testimonies/{testimonyId}/edit', 'TestimonyController@edit');
Route::post('/testimonies/{testimonyId}/edit', 'TestimonyController@update');
Route::post('/testimonies/{testimonyId}/delete', 'TestimonyController@delete');

Route::get('/facilities', 'FacilityController@index');
Route::post('/facilities', 'FacilityController@store');
Route::get('/facilities/new', function () {
	return view('testing.facility.form');
});
Route::get('/facilities/{facilityId}/edit', 'FacilityController@edit');
Route::post('/facilities/{facilityId}/edit', 'FacilityController@update');
Route::post('/facilities/{facilityId}/delete', 'FacilityController@delete');

Route::get('/config/header', 'ConfigurationController@editHeaderSection');
Route::put('/config/header', 'ConfigurationController@updateHeaderSection');

Route::get('/config/service', 'ConfigurationController@editServiceSection');
Route::put('/config/service', 'ConfigurationController@updateServiceSection');

Route::get('/config/room', 'ConfigurationController@editRoomSection');
Route::put('/config/room', 'ConfigurationController@updateRoomSection');

Route::get('/config/general', 'ConfigurationController@editGeneralSection');
Route::put('/config/general', 'ConfigurationController@updateGeneralSection');

Route::get('/config/about', 'ConfigurationController@editAboutSection');
Route::put('/config/about', 'ConfigurationController@updateAboutSection');

Route::post('/media', 'ConfigurationController@addMedia');
Route::delete('/media/{mediaId}', 'ConfigurationController@destroyMedia');

// room route
Route::resource('/rooms','RoomController');
Route::get('rooms/room-images/{id}', 'RoomController@formRemoveImage');

Route::delete('/rooms/room-images/{$id}', 'RoomController@removeImage');
Route::resource('room-facility', 'RoomFacilityController', ['except' => 'show']);


Route::get('/home', 'HomeController@index')->name('home');

Route::group([
	'namespace' => 'Auth'
],
	function () {

		// Authentication Routes...
		$this->get('login', 'LoginController@showLoginForm')->name('login');
		$this->post('login', 'LoginController@login');
		$this->post('logout', 'LoginController@logout')->name('logout');

	});

app/Models/Facility.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Facility extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'image'
    ];

    /**
     * get image url attribute mutator
     *
     * @param $value
     * @return mixed
     */
    public function getImageAttribute($value)
    {
        return Storage::url("facilities/{$value}");
    }
}

app/Http/Controllers/FacilityController.php
<?php

namespace App\Http\Controllers;

use App\Models\Facility;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;


class FacilityController extends Controller
{

    /**
     * FacilityController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $facilities = Facility::all();

        return view('testing.facility.index', [
            'facilities'  => $facilities
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'         => 'required',
            'description'   => 'required',
            'image'         => 'required|image'
        ]);

        if ($request->get('status')) {
            $rules['status'] = [Rule::in(['published', 'unpublished'])];
        }

        $data = $request->only('title', 'description');
        $data['image'] = basename($request->file('image')->store('facilities'));
        $facility = Facility::firstOrCreate([
            'title'         => $data['title'],
            'description'   => $data['description']
        ], [
            'image' => $data['image']
        ]);

        return redirect('/facilities')
                ->with('status', 'success')
                ->with('message', "Facility id: {$facility->id}");
    }

    /**
     * @param $facilityId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function edit($facilityId)
    {
        $facility = Facility::find($facilityId);

        if (!$facility) {
            return redirect('/facilities')
                ->with('status', 'error')
                ->with('message', "Facility not found.");
        }

        return view('testing.facility.form', [
            'facility' => $facility
        ]);
    }

    /**
     * @param Request $request
     * @param $facilityId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $facilityId)
    {
        $facility = Facility::find($facilityId);

        if (!$facility) {
            return redirect('/facilities')
                ->with('status', 'error')
                ->with('message', "Facility not found.");
        }
        if ($request->get('status')) {
            $rules['status'] = [Rule::in(['published', 'unpublished'])];
        }

        $this->validate($request, [
            'title'         => 'sometimes|required',
            'description'   => 'sometimes|required',
            'image'         => 'sometimes|image',
            'status'        => [
                'sometimes',
                Rule::in(['published', 'unpublished'])
            ]
        ]);

        $data = $request->only('title', 'description');

        if (array_key_exists('status', $data) && $data['status'] == 'published') {
            if ((Facility::whereStatus('published')->get())->count() >= 6) {
                return redirect()
                    ->back()
                    ->with('status', 'error')
                    ->message('message', 'Jumlah fasilitas yang dapat ditampilkan melibihi maksimal (6). Silahkan unpublished salah satu terlebih dahulu.');
            }
        }

        if ($request->file('image')) {
            $data['image'] = basename($request->file('image')->store('facilities'));
            Storage::delete('facilities/'.basename($facility->image));
        }

        foreach ($data as $key => $value) {
            $facility->{$key} = $value;
        }

        $facility->save();

        return redirect('/facilities')
                ->with('status', 'success')
                ->with('message', "Facility id: {$facility->id} updated.");

    }

    /**
     * @param $facilityId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($facilityId)
    {
        $facility = Facility::find($facilityId);

        if (!$facility) {
            return redirect('/facilities')
                ->with('status', 'error')
                ->with('message', "Facility not found.");
        }

        if ($facility->delete()) {
            Storage::delete('facilities/'.basename($facility->image));
        } else {
            return redirect('/facilities')
                ->with('status', 'error')
                ->with('message', "Facility id: {$facility->id} delete failed.");
        }

        return redirect('/facilities')
                ->with('status', 'success')
                ->with('message', "Facility id: {$facility->id} deleted.");
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Admin\RoomRequest;
use App\Models\RoomFacility;
use App\Models\RoomImage;
use Carbon\Carbon;
use App\Models\Room;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;

class RoomController extends Controller
{
    /**
     * RoomController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');

    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {   

        $rooms = Room::with('room_facilities','images')->get();

       // dd($rooms);

        return view('testing.room.index', [
            'rooms' => $rooms
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $allFacilities = RoomFacility::all();
        return view('testing.room.form', compact('allFacilities'));
    }

    /**
     * @param RoomRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(RoomRequest $request)
    {
        $room = Room::create($request->all());

        if ($request->images) {
            foreach ($request->images as $image){
                $filename = time() . '.' . $image->getClientOriginalExtension();
                Image::make( $image )->resize( 1280, 720 )->save(storage_path(). '/app/public/rooms/' . $filename );
                Image::make( $image )->fit( 500, 480)->save(storage_path(). '/app/public/rooms/thumbs/' . $filename );
                $image                = new RoomImage();
                $image->src         = $filename;
                $image->room_id = $room->id;
                $image->save();
            }
        }


        if (isset($request->facilities)){
            $room->room_facilities()->sync($request->facilities);
        }else {
            $room->room_facilities()->sync(array());
        }

        return redirect('/rooms')
        ->with('status', 'success')
        ->with('message', "Rooms id: {$room->id}");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $room = Room::with('room_facilities')->find($id);

        if (!$room) {
            return redirect('/rooms')
                ->with('status', 'error')
                ->with('message', "Room not found.");
        }

        $allFacilities = RoomFacility::select('name', 'id')->get();
        $facilities = $room->room_facilities->map(function ($facility) {
            return $facility->id;
        });

        return view('testing.room.form', [
            'room' => $room,
            'allFacilities' => $allFacilities,
            'facilities'    => $facilities->toArray()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $room = Room::find($id);

        if (!$room) {
            return redirect('/rooms')
                ->with('status', 'error')
                ->with('message', "Room not found.");
        }

        if ($request->get('status')) {
            $rules['status'] = [Rule::in(['published', 'unpublished'])];
        }

        $this->validate($request, [
            'name'         => 'sometimes|required',
            'image'         => 'sometimes|image',
            'status'        => [
                'sometimes',
                Rule::in(['published', 'unpublished'])
            ]
        ]);

        $data = $request->only('name', 'detail', 'price', 'status');
        
        if ($request->images) {
            foreach ($request->images as $image){
                $filename = time() . '.' . $image->getClientOriginalExtension();
                Image::make( $image )->resize( 1280, 720 )->save(storage_path(). '/app/public/rooms/' . $filename );
                Image::make( $image )->fit( 500, 480)->save(storage_path(). '/app/public/rooms/thumbs/' . $filename );
                $image                = new RoomImage();
                $image->src         = $filename;
                $image->room_id = $room->id;
                $image->save();
            }
        }

        if (isset($request->facilities)){
            $room->room_facilities()->sync($request->facilities);
        } else {
            $room->room_facilities()->sync(array());
        }


        foreach ($data as $key => $value) {
            $room->{$key} = $value;
        }

        $room->save();

        return redirect('/rooms')
                ->with('status', 'success')
                ->with('message', "Facility id: {$room->id} updated.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $room = Room::find($id);

        if (!$room) {
            return redirect('/rooms')
                ->with('status', 'error')
                ->with('message', "Room not found.");
        }

        if ($room->delete()) {
            Storage::delete('rooms/'.basename($room->image));
        } else {
            return redirect('/rooms')
                ->with('status', 'error')
                ->with('message', "Room id: {$room->id} delete failed.");
        }

        return redirect('/rooms')
                ->with('status', 'success')
                ->with('message', "Room id: {$room->id} deleted.");
    }


    public function formRemoveImage($id){
        $image = RoomImage::findOrFail($id);
        // dd($image);
        return view('testing.room.delete', compact('image'));
    }

    public function removeImage($id)
    {
        $image = RoomImage::find($id);

        if (!$image) {
            return redirect()->back()
                ->with('status', 'error')
                ->with('message', 'Media not found.');
        }

        if (!$image->delete()) {
            return redirect()->back()
                ->with('status', 'error')
                ->with('message', 'Media delete failed.');
        }

        Storage::delete("rooms/{$image->src}");
        
        // return response()->json();

        return redirect()->back()
            ->with('status', 'success')
            ->with('message', 'Media deleted.');
    }

    /**
     * process image to default resolution HD 1024 x 768 for all image upload
     * the image is a resolution height 768px
     *
     * @param $image
     * @return null|string
     */
    private function processImage($image)
    {
        $imageName = str_slug($image->getClientOriginalName(), '-').'-'.(Carbon::now())->toAtomString().'.jpg';
//        $imageName = $image;
        $processedImage = Image::make($image[]);
        $processedImage->resize(null, 768, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
        });
        $startingX = floor(($processedImage->width() / 2) - 512);
        $startingY = floor(($processedImage->height() / 2) - 384);
        $processedImage->crop(1024, 768, $startingX, $startingY);

        if (!Storage::put("rooms/{$imageName}", (string) $processedImage->encode('jpg', 30))) {
            $imageName = null;
        }

        return $imageName;
    }
}

resources/views/testing/room/facility/form.blade.php
@extends('layouts.admin', [
'title' => isset($facility) ? 'Update room facility' .$facility->name : 'New room facility'
])

@section('content')
    <div class="card-body">
        <form method="POST" class="needs-validation" novalidate action="{{ isset($facility) ? url('room-facility/'.$facility->id)  : url('room-facility') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            @if(isset($facility))
                <input type="hidden" name="_method" value="PUT">
            @endif

            <div class="form-group">
                <label for="name" class="control-label">Name</label>
                <input class="form-control" type="text" name="name" value="{{ isset($facility) ? $facility->name : '' }}" placeholder="Name" required>

                <div class="valid-feedback">
                    Looks good!
                </div>

                <div class="invalid-feedback">
                    Please input a name
                </div>
            </div>


            @if(isset($facility))
                <img class="img-fluid img-thumbnail" src="{{ url($facility->image) }}"/>
            @endif

            <div class="form-group">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="image" {{ isset($facility) ?: 'required' }} name="image" accept="image/*" />
                    <label class="custom-file-label" for="image">Choose file</label>
                    <p class="small">Please input your image with hd 1024x768 </p>
                </div>

                <div class="valid-feedback">
                    Looks good!
                </div>

                <div class="invalid-feedback">
                    Please input your image with hd 1024x76
                </div>

            </div>



            <div class="pt-5 d-flex justify-content-center">
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-save"></i>
                    {{ isset($facility) ? 'Update' : 'Save' }}
                </button>
            </div>


        </form>
    </div>
@endsection
@push('styles')
<link rel="stylesheet" type="text/css" href="{{ asset('css/editor.css') }}">
@endpush

@push('scripts')
<script src="{{ asset('js/editor.js') }}"></script>
@endpush

resources/views/testing/room/facility/index.blade.php
@extends('layouts.admin', [
'title' => 'Room',
'url' => route('room-facility.create')
])

@section('content')

    <div class="card-body">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Image</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($facilities as $index => $facility)
                <tr>
                    <td>{{ $index+1 }}</td>
                    <td>{{ $facility->name }}</td>
                    <td><img height="30px" src="{{ url($facility->image) }}"/></td>
                    <td class="btn-group" role="group">
                        <a class="btn btn-sm btn-warning" href="{{ route('room-facility.edit', $facility->id) }}" data-tooltip="tooltip" title="Edit">
                            <i class="fa fa-edit"></i>
                        </a>

                        <a href="{{ route('room-facility.destroy', $facility->id) }}" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete"  data-tooltip="tooltip" title="Delete">
                            <i class="fa fa-trash"></i>
                        </a>

                        <!-- Modal -->
                        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Delete room</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure delete room facility {{ $facility->name }}?
                                    </div>
                                    <div class="modal-footer">
                                        <form method="POST" action="{{ route('room-facility.destroy', $facility->id) }}">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection
@push('scripts')
<script src="{{ asset('js/datatable.js') }}"></script>
@endpush