routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomePageController@index');
Route::get('our-room/{slug}', 'HomePageController@room')->name('our-room');
Route::get('/book-room', 'HomePageController@bookRoom')->name('book-room');

Route::get('/testimonies', 'TestimonyController@index');
Route::post('/testimonies', 'TestimonyController@store');
Route::get('/testimonies/new', function () {
	return view('testing.testimony.form');
});
Route::get('/testimonies/{testimonyId}/edit', 'TestimonyController@edit');
Route::post('/testimonies/{testimonyId}/edit', 'TestimonyController@update');
Route::post('/testimonies/{testimonyId}/delete', 'TestimonyController@delete');

Route::get('/facilities', 'FacilityController@index');
Route::post('/facilities', 'FacilityController@store');
Route::get('/facilities/new', function () {
	return view('testing.facility.form');
});
Route::get('/facilities/{facilityId}/edit', 'FacilityController@edit');
Route::post('/facilities/{facilityId}/edit', 'FacilityController@update');
Route::post('/facilities/{facilityId}/delete', 'FacilityController@delete');

Route::get('/config/header', 'ConfigurationController@editHeaderSection');
Route::put('/config/header', 'ConfigurationController@updateHeaderSection');

Route::get('/config/service', 'ConfigurationController@editServiceSection');
Route::put('/config/service', 'ConfigurationController@updateServiceSection');

Route::get('/config/room', 'ConfigurationController@editRoomSection');
Route::put('/config/room', 'ConfigurationController@updateRoomSection');

Route::get('/config/general', 'ConfigurationController@editGeneralSection');
Route::put('/config/general', 'ConfigurationController@updateGeneralSection');

Route::get('/config/about', 'ConfigurationController@editAboutSection');
Route::put('/config/about', 'ConfigurationController@updateAboutSection');

Route::post('/media', 'ConfigurationController@addMedia');
Route::delete('/media/{mediaId}', 'ConfigurationController@destroyMedia');

// room route
Route::resource('/rooms','RoomController');
Route::get('rooms/room-images/{id}', 'RoomController@formRemoveImage');

Route::delete('/rooms/room-images/{$id}', 'RoomController@removeImage');
Route::resource('room-facility', 'RoomFacilityController', ['except' => 'show']);


Route::get('/home', 'HomeController@index')->name('home');

Route::group([
	'namespace' => 'Auth'
],
	function () {

		// Authentication Routes...
		$this->get('login', 'LoginController@showLoginForm')->name('login');
		$this->post('login', 'LoginController@login');
		$this->post('logout', 'LoginController@logout')->name('logout');

	});

resources/views/_partials/breadcrumb.blade.php
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>{{ $title or config('site.title') }}</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    @for($i = 0; $i <= count(Request::segments()); $i++)
                        <li>
                            <a href="">{{Request::segment($i)}}</a>
                            @if($i < count(Request::segments()) & $i > 0)
                            @endif
                        </li>
                    @endfor
                </ol>
            </div>
        </div>
    </div>
</div>

resources/views/_partials/card-header.blade.php
@if(isset($title))
<div class="row card-header">
    <div class="col">
        <h3 class="card-title">{{ $title or 'Dashboard' }}</h3>
    </div>

    @if(isset($url))
        <div class="col text-right">
            <a class="btn btn-sm btn-primary" href="{{ $url }}"><i class="fa fa-plus"></i> New</a>
        </div>
    @endif
    @if(isset($show))
        <div class="col text-right">
            <a class="btn btn-sm btn-warning" href="{{ $show }}"><i class="fa fa-eye"></i> Show</a>
        </div>
    @endif
</div>
@endif

resources/views/_partials/header.blade.php
<!-- Header-->
<header id="header" class="header">

    <div class="header-menu">

        <div class="col-sm-7">
            <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
        </div>

        <div class="col-sm-5">
            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="/storage/images/admin.jpg" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">

                    <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fa fa-power-off"></i> Logout</a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </div>

        </div>
    </div>

</header><!-- /header -->
<!-- Header-->

resources/views/_partials/sidenav.blade.php
<!-- Left Panel -->

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/" style="font-size: 20px;">{{ config('app.name')." CMS" }}</a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ url('/home') }}"> <i class="menu-icon fa fa-home"></i>Home </a>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="menu-icon fa fa-hotel"></i>Rooms</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-circle"></i><a href="{{ route('rooms.index') }}">Rooms</a></li>
                        <li><i class="fa fa-circle"></i><a href="{{ route('rooms.create') }}">Creating room</a></li>
                        <li><i class="fa fa-circle"></i><a href="{{ route('room-facility.index') }}">Room Facility</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="menu-icon fa fa-bath"></i>Services</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-circle"></i><a href="{{ url('facilities') }}">All services</a></li>
                        <li><i class="menu-icon fa fa-circle"></i><a href="{{ url('facilities/new') }}">create Facility</a></li>
                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="menu-icon fa fa-user-circle"></i>Testimonies</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-users"></i><a href="{{ url('testimonies') }}">All testimonies</a></li>
                        <li><i class="menu-icon fa fa-user-o"></i><a href="{{ url('testimonies/new')}}">create testimoni</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="menu-icon fa fa-cog"></i>Setting</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-check"></i><a href="{{ url('config/header') }}">Header</a></li>
                        <li><i class="menu-icon fa fa-check"></i><a href="{{ url('config/service') }}">Service</a></li>
                        <li><i class="menu-icon fa fa-check"></i><a href="{{ url('config/room') }}">Room</a></li>
                        <li><i class="menu-icon fa fa-check"></i><a href="{{ url('config/about') }}">About </a></li>
                        <li><i class="menu-icon fa fa-check"></i><a href="{{ url('config/general') }}">General</a></li>
                    </ul>
                </li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->